<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="EPBYMINW5030" failures="1" tests="1" name="pow test" time="0.006" errors="0" timestamp="01 Apr 2019 07:42:05 GMT">
  <testcase classname="alex.PowTest" name="ctgTest" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [42.22425314473263] but found [32.0]">
      <![CDATA[java.lang.AssertionError: expected [42.22425314473263] but found [32.0]
at alex.PowTest.ctgTest(PowTest.java:15)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ctgTest -->
</testsuite> <!-- pow test -->
